### ISSUE TITLE
Example using data from AstroAPI

### ISSUE THREAD

**Issue by yayromina** [AstroDraw/AstroChart#10]
Hi there, I am using the SwissEphemeris API, and the numbers I'm getting for latitude/longitude of planets doesn't look like what's being passed in these examples, and I'm not sure how to set up sign/house positions. Do you have any examples of parsing data from this API?

**Comment by afucher** [comment]
Hey @yayromina , sorry but I don't know how this API works.
Today we have samples about how we expect the data independent of the source, you can take a look to our [examples](https://github.com/AstroDraw/AstroChart/tree/main/project/examples)

**Comment by afucher** [comment]
Hey @yayromina closing this, if you have any question, please open a [discussion](https://github.com/AstroDraw/AstroChart/discussions).
