### ISSUE TITLE
Add South Node Symbol

### ISSUE THREAD

**Issue by zmark9** [AstroDraw/AstroChart#15]
**Additional context**  

Hi Was wondering about adding the South Node symbol?

I can contribute with just about everything else creating the code around that aside from the "d" attribute which defines the symbol. I have attempted this to no avail and I an otherwise attaching an SVG file of the South Node and North Node for compatibility sake, which is otherwise very similar to the current North Node. I even tried inverting the North Node but also to no avail. I would also like to understand how the code uses that vs. the "d" attribute in the SVG file.. still an SVG novice. 

Thanks in advance. Mark 

![South-Node](https://user-images.githubusercontent.com/32187855/155454078-41a60179-4f2f-4bc2-946a-a383e7b00738.svg)
![North-Node](https://user-images.githubusercontent.com/32187855/155454089-f8c19520-6399-47ac-b5c2-a19de45c8d29.svg)

**Comment by afucher** [comment]
Hey @zmark9 , nice that you have interest into add `South Node symbol`

About the use of the svg in the source code, you can take a look to some of the existing symbols that we have, [here](https://github.com/AstroDraw/AstroChart/blob/main/project/src/svg.js#L249) you can check the North Node example. We just append an svg element, and then we add all the content manually setting the specific attributes.

I don't know if this can help you, please let me know if you need anymore information

**Comment by aintHuman** [comment]
Please add south node.
