### ISSUE TITLE
Build missing?

### ISSUE THREAD

**Issue by GuyVervilleSpiria** [AstroDraw/AstroChart#16]
I think your build is missing compare to https://github.com/Kibo/AstroChart/tree/master/project
It's only available in the release section: https://github.com/AstroDraw/AstroChart/releases

**Comment by afucher** [comment]
Hey @GuyVervilleSpiria I don't know if I understood correctly your question.
But, in this new repo we are not adding it to the source code. We are just leaving it in the release section.
Was this your question? Is this an issue?

**Comment by GuyVervilleSpiria** [comment]
Hello, it’s ok. Thanks.

Guy
www.guyverville.com<http://www.guyverville.com>

De : Arthur Fücher ***@***.***>
Date : mercredi, 23 mars 2022 à 16:43
À : AstroDraw/AstroChart ***@***.***>
Cc : Guy Verville ***@***.***>, Mention ***@***.***>
Objet : Re: [AstroDraw/AstroChart] Build missing? (Issue #16)

Hey @GuyVervilleSpiria<https://github.com/GuyVervilleSpiria> I don't know if I understood correctly your question.
But, in this new repo we are not adding it to the source code. We are just leaving it in the release section.
Was this your question? Is this an issue?
