### ISSUE TITLE
AstroChart - V3

### ISSUE THREAD

**Issue by afucher** [AstroDraw/AstroChart#21]
This new version aims to make some improvements in tooling and internal improvements:

- [x]  #18 
- [x] Add linter
- [x] #22
- [x] #19 
- [x] #13 
- [x] Publish cdn (https://unpkg.com/@astrodraw/astrochart)
- [x] Add lint
- [ ] #52

Replicate contributions from v2:

- [x] #25  [commit](https://github.com/AstroDraw/AstroChart/commit/50462a37e8cfcca1cca62d66d0bea65dc05150a8)
- [x] #26  [commit](https://github.com/AstroDraw/AstroChart/commit/8695ccc1234d6bcc4770c5a2f0c2c7c97b3741dc)

Branch: [v3-dev](https://github.com/AstroDraw/AstroChart/tree/v3-dev)

**Comment by jeferson-sb** [comment]
@afucher Hey, what is current status of this new version?

**Comment by afucher** [comment]
Hey @jeferson-sb , it is still in progress, but I'll probably finish it in the next year. My daughter was born, so I'm giving less focus here in the project.
In [this branch](https://github.com/AstroDraw/AstroChart/tree/v3-dev) you can find the latest version, I'm using it in a personal project and it was working good. If you want to test it, please feel free.
Also, it is already published in the [NPM](https://www.npmjs.com/package/@astrodraw/astrochart).
Are you planning to use it in a project?

**Comment by jeferson-sb** [comment]
@afucher yes, I was really looking for a package version of it, good to know there is some progress already on npm :) 
Also, congrats on the birth of your daughter! <3

**Comment by afucher** [comment]
thanks @jeferson-sb :)
Can you share the project? I'm curious about where this library is being used. 
Also, with the v3 I started the https://github.com/AstroDraw/astrodraw.github.io, and there I'm using the npm version.

**Comment by jeferson-sb** [comment]
@afucher it's a project for a company I'm working at. https://soulloop.com/ 
I got it working just on our internal dashboard and stuff, but I might have to look for a react-native option to use in the app.

**Comment by afucher** [comment]
Just released the v3.0.0-rc1, please checkout https://github.com/AstroDraw/AstroChart/discussions/39

**Comment by afucher** [comment]
Main branch now is with the v3 version. (v3.0.0-rc5 already on npm).
Soon will release the final v3.0.0 version, and close the issue.
Please let me know, if someone find any issue
