### ISSUE TITLE
Have you had any Docs to use this repo ? I think this maybe usefull for user

### ISSUE THREAD

**Issue by thang551999** [AstroDraw/AstroChart#23]

**Comment by afucher** [comment]
Hello @thang551999 , today we just have the README and some [examples](https://github.com/AstroDraw/AstroChart/tree/main/project/examples)
I'm working in the `v3` version, and for this version we will have this: https://astrodraw.github.io/

**Comment by afucher** [comment]
If you have any question about how to use, please use the discussion here in the repo.
