### ISSUE TITLE
Wrong order on planets position

### ISSUE THREAD

**Issue by cptolemy** [AstroDraw/AstroChart#3]
Good afternoon,

I realized that now this is the right place to report bugs - even if previous - from the previous astrochart repo.

The routines are working great, but I found a small bug. If you look at the chart I send attached, at the red zone, you see that the planets are in the right place but in a litle bit "messy order". For instance, Saturn should be in Neptune's place - the line would be direct and closer and they wouldn't cross each other.

At the time, I changed the collision radius. But it solved one of them. Not all.
I think the question is the order in degrees. Let's say that Mars and Jupiter are respectively in 15 and 10 Taurus. In the routine, Jupiter should be runned first because its longitude is less than Mars, even if in the array is in second, for example.

Has this problem been aproached? If yes, in which line/routine?

Best regards,

Kepler

![kibo80940803-b194e900-8dd8-11ea-8cd3-c45c69506967](https://user-images.githubusercontent.com/15618062/111364833-a31a8d80-8689-11eb-9f77-a290e1524104.png)

**Comment by marcilioware** [comment]
> Good afternoon,
> 
> I realized that now this is the right place to report bugs - even if previous - from the previous astrochart repo.
> 
> The routines are working great, but I found a small bug. If you look at the chart I send attached, at the red zone, you see that the planets are in the right place but in a litle bit "messy order". For instance, Saturn should be in Neptune's place - the line would be direct and closer and they wouldn't cross each other.
> 
> At the time, I changed the collision radius. But it solved one of them. Not all.
> I think the question is the order in degrees. Let's say that Mars and Jupiter are respectively in 15 and 10 Taurus. In the routine, Jupiter should be runned first because its longitude is less than Mars, even if in the array is in second, for example.
> 
> Has this problem been aproached? If yes, in which line/routine?
> 
> Best regards,
> 
> Kepler
> 
> ![kibo80940803-b194e900-8dd8-11ea-8cd3-c45c69506967](https://user-images.githubusercontent.com/15618062/111364833-a31a8d80-8689-11eb-9f77-a290e1524104.png)

Hi! Did you find any workaround?

**Comment by marcilioware** [comment]
Hi! Did you find any workaround?

**Comment by afucher** [comment]
Hey @cptolemy , 

This is a known bug, but I don't have time yet to work on it.
Seems that is some cases the collision radius works, but as you mentioned not all the cases are covered.

I will try to take a look in the next week, I have some other cases that this happen also.

**Comment by afucher** [comment]
Hi! 

I made some changes, and here worked for the cases that I have.

I still need to add more tests, but if you want to test, you can use [this version](https://github.com/AstroDraw/AstroChart/tree/fix-collision/project/build)

**Comment by cptolemy** [comment]
Good afternoon afucher

I am very sorry for the late reply. 

Thank you very much - I will test it. Could you please indicate to me what exactly did you changed or added (what routine and/or lines) regarding the original, please?

Regards,

CPtolemy

**Comment by afucher** [comment]
Sure, you can check the changes [here](https://github.com/AstroDraw/AstroChart/commit/ba7848b1f83e996401c760815f96ce0ae7117eca#diff-6b57aa89733260eeea0b5914a9dc4351908ade42b43354e42fee85f9d3dcd8c8), most of the part was in the `placePointsInCollision` function.

**Comment by afucher** [comment]
@cptolemy I made more tests locally and seems that is all good. I merged the solution, but feel free to reopen the issue if you find any error.

**Comment by cptolemy** [comment]
Good afternoon afucher,

Thank you very much. It seems to be working very well. 
But I will input some more pretty complicated cases when I have the time :)

However, I have the feeling that is solved - the code makes 100% sense. Congratulations.

Regards, and many thanks,

CPtolemy
