### ISSUE TITLE
wat is there no aspect in my chart?  and the sirius is a red point not symbol?

### ISSUE THREAD

**Issue by kiloppertry** [AstroDraw/AstroChart#66]
**Describe the bug**
A clear and
![QQ截图20231129123711](https://github.com/AstroDraw/AstroChart/assets/39750125/2c00eaea-e57c-4b4f-8a6f-fff176a29080)
![QQ截图20231129123427](https://github.com/AstroDraw/AstroChart/assets/39750125/52f8ce9f-b59f-4d26-b750-ee1fab971661)
 concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional info (please complete the following information):**

**Additional context**

**Comment by kiloppertry** [comment]
i use react.js:
    const chart = new Chart("paper", 800, 800);
    chart.radix(data);


          <Box sx={{ position: "fixed", left: "5%", top: "5%" }}>
            <div id="paper"></div>
          </Box>

**Comment by afucher** [comment]
Answered in the [discussion topic](https://github.com/AstroDraw/AstroChart/discussions/67)
